---
- name: Database Clients
  hosts: localhost
  ignore_errors: yes
  become: true
  tasks:
    - name: DBeaver Repository
      apt_repository: repo=ppa:serge-rider/dbeaver-ce
      tags:
        - default

    - name: DBeaver Community
      apt: name=dbeaver-ce
      tags:
        - default

    - name: Usql
      runscript:
        script: usql.sh
        creates: /usr/bin/usql
      tags:
        - default

    - name: Datagrip Trial
      snap: name=datagrip classic=yes
      tags:
        - datagrip_trial

    - name: MySQL Workbench Community
      snap: name=mysql-workbench-community classic=yes
      tags:
        - mysql

    - name: mycli
      pip: name=mycli
      tags:
        - mysql

    - name: pgAdmin 4 Desktop Key
      apt_key: url=https://www.pgadmin.org/static/packages_pgadmin_org.pub
      tags:
        - postgres

    - name: pgAdmin 4 Desktop Repository
      apt_repository:
        repo: deb https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/jammy pgadmin4 main
      tags:
        - postgres

    - name: pgAdmin 4 Desktop
      apt: 
        pkg:
          - libpq5
          - pgadmin4-desktop
      tags:
        - postgres

    - name: pgcli
      apt: name=pgcli
      tags:
        - postgres

    - name: SQLite Browser Repo
      apt_repository: repo=ppa:linuxgndu/sqlitebrowser
      tags:
        - sqlite

    - name: SQLite Browser
      apt: name=sqlitebrowser
      tags:
        - sqlite

    - name: Redis Commander
      npm: name=redis-commander global=yes
      tags:
        - redis

    - name: MongoDB Compass
      apt: deb=https://downloads.mongodb.com/compass/mongodb-compass_1.30.1_amd64.deb
      tags:
        - mongodb
