---
- name: General
  hosts: localhost
  become: true
  ignore_errors: yes
  tasks:
    - name: VSCode Key
      apt_key: url=https://packages.microsoft.com/keys/microsoft.asc
      tags:
        - default

    - name: VSCode Repository
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
      tags:
        - default

    # The "default" editor, with extensions in each ecosystem
    - name: VSCode
      apt: name=code
      tags:
        - default
 
    - name: VSCode Intellicode 
      vscodeextension: name=VisualStudioExptTeam.vscodeintellicode
      tags:
        - default

    # For some reason, it's not always saving to the backup dir!
    # This is a VERY useful tool that has saved many butts... fix!
    #- name: VSCode File Backup 
    #  vscodeextension: name=purplestone.savebackup
    #  tags:
    #    - default

    #- name: VSCode File Backup directory adjustments
    #  runscript:
    #    script: /vscode_backup_create_dir.sh
    #    creates: .vscode/saveBackup
    #  tags:
    #    - default

    - name: Terminator
      apt: name=terminator
      tags:
        - default

    - name: Screen
      apt: name=screen
      tags:
        - default

    - name: Tmux
      apt: name=tmux
      tags:
        - default

    - name: Vim 
      apt: name=vim
      tags:
        - default

    - name: Emacs Repository
      apt_repository: repo=ppa:kelleyk/emacs
      tags:
        - default

    - name: Emacs
      apt: name=emacs28
      tags:
        - default

    - name: Htop
      apt: name=htop
      tags:
        - default

    - name: ripgrep
      apt: name=ripgrep
      tags:
        - default

    - name: fd 
      apt: name=fd-find
      tags:
        - default

    - name: fzf
      apt: name=fzf
      tags:
        - default

    - name: jq
      apt: name=jq
      tags:
        - default

    - name: thefuck
      apt: name=thefuck
      tags:
        - default

    - name: unrar
      apt: name=unrar
      tags:
        - default

    - name: 7-Zip
      apt: name=p7zip-full
      tags:
        - default

    - name: dos2unix
      apt: name=dos2unix
      tags:
        - default

    - name: tree
      apt: name=tree
      tags:
        - default