---
- name: Go
  hosts: localhost
  ignore_errors: yes
  become: true
  tasks:
    - name: Bison dependency
      apt: name=bison
      tags:
        - default

    - name: Go Repository
      apt_repository: repo=ppa:longsleep/golang-backports
      tags:
        - default

    - name: Go
      apt: name=golang-go
      tags:
        - default

    - name: Go Version Manager
      runscript:
        script: gvm.sh
        creates: .gvm
        shared: true
      tags:
        - default

    - name: VSCode Go
      vscodeextension: name=golang.Go
      tags:
        - default

    - name: GoLand Trial
      snap: name=goland classic=yes
      tags:
        - goland_trial