---
- name: Java
  hosts: localhost
  ignore_errors: yes
  become: true
  tasks:
    - name: Java 17
      apt:
        pkg:
          - openjdk-17-jre
          - openjdk-17-jdk
      tags:
        - default

    - name: VSCode Java
      vscodeextension: name=vscjava.vscode-java-pack
      tags:
        - default

    - name: Maven
      apt: name=maven
      tags:
        - default

    - name: Gradle
      runscript:
        script: gradle.sh
        creates: /usr/local/bin/gradle
      tags:
        - default

    - name: Eclipse
      runscript:
        script: eclipse_java.sh
        creates: /usr/bin/eclipse
      tags:
        - eclipse_java

    - name: Spring Tool Suite 
      runscript:
        script: eclipse_sts.sh
        creates: /usr/bin/eclipse-sts
      tags:
        - eclipse_sts

    - name: IntelliJ IDEA Community
      snap: name=intellij-idea-community classic=yes
      tags:
        - intellij

    - name: Jabba Version Manager
      runscript:
        script: jabba.sh
        creates: .jabba
      tags:
        - default

    - name: Ant
      apt: name=ant
      tags:
        - ant

    - name: Ivy
      apt: name=ivy
      tags:
        - ant