---
- name: Python
  hosts: localhost
  ignore_errors: yes
  become: true
  tasks:

    # Python is not included in this playbook as it was installed in the base installer.
    # This project relies heavily on Python for the processing that comes before running Ansible.

    - name: VSCode Python
      vscodeextension: name=ms-python.python
      tags:
        - default

    - name: Pipx
      pip: name=pipx
      tags:
        - default

    - name: Flake8
      pip: name=flake8
      tags:
        - flake8

    - name: Black
      pip: name=black
      tags:
        - black
 
    - name: Pipenv
      apt: name=pipenv
      tags:
        - pipenv

    - name: Poetry
      runscript:
        script: poetry.sh
        creates: .poetry/bin/poetry
        shared: true
      tags:
        - poetry

    - name: Pyenv
      runscript:
        script: pyenv.sh
        creates: .pyenv/bin/pyenv
      tags:
        - pyenv

    # Using the lightweight Miniconda solution, we can leverage the Conda
    # package manager. It serves as a nice general purpose package manager.
    - name: Conda Package Manager
      runscript:
        script: miniconda.sh
        creates: .miniconda
      tags:
       - conda

    - name: Python venv
      apt: name=python3.10-venv
      tags:
        - default

    - name: PyCharm Community
      snap: name=pycharm-community classic=yes
      tags:
        - pycharm