---
- name: Ruby
  hosts: localhost
  ignore_errors: yes
  become: true
  tasks:

    # This playbooks is VERY BUGGY. Refer to this issue: https://github.com/programmers/system_qa/issues/9
    # ...and, as always, contributions are very welcomed.

    - name: RubyMine Trial
      snap: name=rubymine classic=yes
      tags:
        - rubymine_trial

#    - name: rvm
#      runscript:
#        script: rvm.sh
#        creates: /usr/share/rvm/bin/rvm
#      tags:
#        - default
#
#    - name: Ruby
#      runscript:
#        script: Ruby.sh
#        creates: /usr/share/rvm/rubies/ruby-3.1.2/bin/ruby
#      tags:
#        - default
#
#    - name: VSCode Ruby
#      vscodeextension: name=rebornix.Ruby
#      tags:
#        - default
#
#    - name: Bundler
#      runscript:
#        script: bundler.sh
#        creates: /usr/share/rvm/gems/ruby-3.1.2/bin/bundler
#      tags:
#        - default
#
