- name: Rust
  hosts: localhost
  ignore_errors: yes
  become: true
  tasks:
    - name: Rust (via Rustup)
      runscript:
        script: rust.sh
        shared: true
        creates: .cargo/bin/rustc
      tags:
        - default

    - name: VSCode Rust
      vscodeextension: name=rust-lang.rust
      tags:
        - default